language: ruby
rvm:
  - 2.2.8
  - 2.2.9
  - 2.3.5
  - 2.3.6
  - 2.4.2
  - 2.4.3
  - 2.5.0

services:
  - mysql

before_install:
  - gem install bundler
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'

env:
  - USE_MYSQL=true

git:
  depth: 1
