language: ruby
rvm:
  - 2.2.3
  - 2.2.6
  - 2.2.7
  - 2.3.3
  - 2.3.4
  - 2.4.0
  - 2.4.1

services:
  - mysql

before_install:
  - gem install bundler
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'

env:
  - USE_MYSQL=true

git:
  depth: 1
